### ISSUE TITLE
Working with categorical and binary traits

### ISSUE THREAD

**Issue by zcebeci** [jiabowang/GAPIT#57]
The GAPIT3 produces many warning message regarding memory.size is depreciated.  Also, could you please add some examples to work with categorical and binary traits? 
Thanks in advance.

**Comment by jiabowang** [comment]
Hi @zcebeci ,

In the GAPIT, all phenotype values would be consumed as continued traits and following a normal distribution.
So the categorical and binary traits will be considered as continued traits. Because the mean and variance of all traits were used to estimate parameters in the fixed and random sections of models.
All models in the GAPIT are linear models. Maybe machine learning would supply more efficient detection.
